### ISSUE TITLE
All docker images are pulling "latest"

### ISSUE THREAD

**Issue by kojustin** [fnproject/fn-helm#23]
In the helm charts all the FN images are pulled as "latest". This is not safe, this will indiscriminately pull in changes from fnproject/fn even if they haven't been tested yet in a Helm deployment. We should change to a model where fn-helm pulls in images by fixed version tags and we update the helm changes only after we've validated that the deployments and services work with new changes from upstream.

**Comment by denismakogon** [comment]
It’s in configuration values. `latest` tag is a default value, so you should be able to change that.

**Comment by denismakogon** [comment]
See https://github.com/fnproject/fn-helm/blob/master/fn/values.yaml
