### ISSUE TITLE
Load Balancing between pods

### ISSUE THREAD

**Issue by Kuvesz** [fnproject/fn-helm#37]
Hi!

I'm not sure how the fn load balancer works, at least as far as I know it load balances between fn server instances. The question is if this Kubernetes solution has any knid of autoscaling or can I set the number of pods to run fn somehow? I know my question is a bit all over the place but I'm not really good with Kubernetes and have only ever really used fn on a single node before.

Thanks in advance for any info!

**Comment by denismakogon** [comment]
please check the latest charts, because a lot things changed, closing for now.
